"""Tests for the 2026-05-24 audit round 3 fix: surface reliability
chips + Pass 2 verdicts + reasoning in the HTML dashboard.

Round 2 (PR #67) added these to the TEXT report (format_report). The
HTML dashboard is generated by a separate code path
(generate_html_dashboard) which was NOT updated — meaning the
operator-facing surface didn't show what the engine knew.

Evidence: SATS dashboard rendered today showed `σ 61%` in the
metadata but no near-IGARCH warning, no σ-divergence warning, no
weak-signals warning — even though the engine's text report had
all three.
"""
from __future__ import annotations

import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.reporter import _reliability_chips, _reliability_chips_html


def _make_vol_profile(alpha_plus_beta=0.50, divergence=5.0):
    return SimpleNamespace(
        garch_alpha_plus_beta=alpha_plus_beta,
        triangulation={"divergence": divergence, "blended": 0.50, "anchors": {}},
    )


def _make_signal(confidence="HIGH", is_absent=False):
    return SimpleNamespace(confidence=confidence, is_absent=is_absent)


# =============================================================================
# _reliability_chips — shared helper used by both text + HTML renderers
# =============================================================================

def test_chips_returns_label_and_severity_tuples():
    chips = _reliability_chips(
        vol_profile=_make_vol_profile(alpha_plus_beta=0.9999, divergence=20.0),
        base_signals=[_make_signal("HIGH")] * 12,
        sigma_class_mismatch="auto MID, hint HIGH",
    )
    # near-IGARCH (red), σ divergence (orange), σ-class mismatch (yellow)
    assert len(chips) == 3
    severities = [sev for _, sev in chips]
    assert "red" in severities
    assert "orange" in severities
    assert "yellow" in severities


def test_chips_empty_on_clean_run():
    chips = _reliability_chips(
        vol_profile=_make_vol_profile(),
        base_signals=[_make_signal("HIGH")] * 12,
        sigma_class_mismatch=None,
    )
    assert chips == []


# =============================================================================
# _reliability_chips_html — HTML dashboard rendering
# =============================================================================

def test_html_empty_on_clean_run():
    """Clean run → empty string (no chips bar on operator dashboard)."""
    html = _reliability_chips_html(
        vol_profile=_make_vol_profile(),
        base_signals=[_make_signal("HIGH")] * 12,
        sigma_class_mismatch=None,
    )
    assert html == ""


def test_html_includes_reliability_bar_when_chips_fire():
    """SATS case from production smoke 2026-05-24: near-IGARCH +
    σ divergence + weak signals all fire. HTML must render."""
    base = [_make_signal("HIGH")] * 3 + [_make_signal("LOW")] * 9
    html = _reliability_chips_html(
        vol_profile=_make_vol_profile(alpha_plus_beta=0.9999, divergence=19.3),
        base_signals=base,
        sigma_class_mismatch="auto MID, hint HIGH",
    )
    assert 'class="reliability-bar"' in html
    assert "RELIABILITY:" in html
    assert "near-IGARCH" in html
    assert "0.9999" in html
    assert "19.3pp" in html
    assert "3/12 signals active" in html
    assert "registry hint stale" in html


def test_html_severity_colors_present():
    """Each chip gets a severity-specific background color so the
    operator can spot high-severity flags at a glance."""
    base = [_make_signal("HIGH")] * 3 + [_make_signal("LOW")] * 9
    html = _reliability_chips_html(
        vol_profile=_make_vol_profile(alpha_plus_beta=0.9999, divergence=19.3),
        base_signals=base,
        sigma_class_mismatch="auto MID, hint HIGH",
    )
    # near-IGARCH (red)
    assert "#7f1d1d" in html
    # σ divergence + weak signals (orange)
    assert "#7c2d12" in html
    # σ-class mismatch (yellow)
    assert "#713f12" in html


def test_html_one_chip_only_renders_bar_once():
    """Single chip still produces full bar (prefix + chip)."""
    html = _reliability_chips_html(
        vol_profile=_make_vol_profile(alpha_plus_beta=0.99),
        base_signals=[_make_signal("HIGH")] * 12,
        sigma_class_mismatch=None,
    )
    assert html.count('class="reliability-bar"') == 1
    assert "near-IGARCH" in html
    assert "σ divergence" not in html
    assert "registry hint stale" not in html


def test_chips_use_real_volprofile_divergence_pp_attribute():
    """Regression guard against the round-3 mock-vs-reality bug:
    the real VolProfile dataclass exposes divergence as the
    `divergence_pp` attribute (engine.py:147), NOT as a triangulation
    dict. The chip helper must handle both shapes."""
    from src.engine import VolatilityProfile
    # Real dataclass instance — mirrors what engine.run_pipeline builds.
    real_vp = VolatilityProfile(
        garch_sigma=0.58, garch_alpha=0.05, garch_beta=0.95,
        garch_alpha_plus_beta=0.9999,
        realized_30d=0.56, realized_60d=0.58, realized_90d=0.58,
        options_iv=0.755, options_dte=54,
        blended_sigma=0.612, anchors_count=5, divergence_pp=19.3,
        near_unit_root=True,
    )
    chips = _reliability_chips(
        vol_profile=real_vp,
        base_signals=[_make_signal("HIGH")] * 12,
        sigma_class_mismatch=None,
    )
    chip_labels = [label for label, _ in chips]
    # Both near-IGARCH AND σ divergence must fire with real data
    assert any("near-IGARCH" in label for label in chip_labels), chip_labels
    assert any("σ divergence" in label and "19.3pp" in label
               for label in chip_labels), chip_labels


def test_html_defensive_on_missing_vol_profile_attrs():
    """Bare SimpleNamespace without expected attrs → empty HTML,
    no crash. Defensive against test mocks / future schema changes."""
    bare = SimpleNamespace()
    html = _reliability_chips_html(
        vol_profile=bare,
        base_signals=[],
        sigma_class_mismatch=None,
    )
    assert html == ""


# =============================================================================
# Text + HTML stay in sync — same chip data drives both renderers
# =============================================================================

def test_text_and_html_agree_on_chip_count():
    """The text-report _reliability_warnings_line and HTML
    _reliability_chips_html must surface the same flags — they share
    _reliability_chips. Regression guard against divergence."""
    from src.reporter import _reliability_warnings_line

    base = [_make_signal("HIGH")] * 3 + [_make_signal("LOW")] * 9
    vol = _make_vol_profile(alpha_plus_beta=0.9999, divergence=19.3)

    chips = _reliability_chips(vol_profile=vol, base_signals=base,
                                 sigma_class_mismatch="x")
    text_line = _reliability_warnings_line(vol_profile=vol, base_signals=base,
                                             sigma_class_mismatch="x")
    html = _reliability_chips_html(vol_profile=vol, base_signals=base,
                                     sigma_class_mismatch="x")

    # Both renderers reflect every chip
    for label, _ in chips:
        assert label in text_line, f"text missing chip: {label}"
        assert label in html, f"html missing chip: {label}"


# =============================================================================
# HTML AI block — Pass 2 catalyst verdicts + reasoning surfaced
# =============================================================================

def test_html_dashboard_renders_agreement_chip(tmp_path):
    """generate_html_dashboard must surface Pass 2's agreement tag."""
    from src.engine import AIPassOutput
    from src.reporter import generate_html_dashboard

    pass1 = AIPassOutput(
        pass_number=1, drift_estimate=0.15, drift_range=(-0.10, 0.40),
        confidence="MEDIUM", vol_regime="MEDIUM", narrative_score="strong",
        catalysts=[], bull_factors=[], bear_factors=[], key_risks=[],
        revision_from_prior_pass=None, cost_usd=0.10, raw_sources_cited=4,
    )
    pass2 = AIPassOutput(
        pass_number=2, drift_estimate=0.10, drift_range=(0.0, 0.20),
        confidence="LOW", vol_regime="MEDIUM", narrative_score="strong",
        catalysts=[
            {"name": "Q1 earnings", "magnitude": "high",
             "direction_risk": "bullish",
             "verification_verdict": "VERIFIED",
             "verification_reasoning": "Confirmed by SEC 8-K"},
        ],
        bull_factors=[], bear_factors=[],
        key_risks=["risk"],
        revision_from_prior_pass=-0.05, cost_usd=0.04, raw_sources_cited=0,
        agreement_with_pass1="strong_disagree",
        revision_reasoning="Math layer shows near-symmetric touch probs",
    )
    snapshot = SimpleNamespace(
        ticker="TEST",
        timestamp=__import__("datetime").datetime(2026, 5, 24, 14, 30),
        spot=100.0, ytd_return=0.30,
    )
    vol_profile = _make_vol_profile(alpha_plus_beta=0.70, divergence=5.0)
    vol_profile.blended_sigma = 0.40
    method_check = {"refused": False, "flags": [], "table": []}
    backtest = {"sufficient_data": False, "n_samples": 0,
                "message": "N=0"}

    out = tmp_path / "test_dashboard.html"
    generate_html_dashboard(
        out, snapshot, None, vol_profile, [], pass1, pass2,
        method_check, backtest, [],
        conviction_dip=0.65, conviction_rally_cond=0.70,
        horizon_days=60,
    )
    html_text = out.read_text()

    # Agreement chip surfaced
    assert "STRONG DISAGREE" in html_text
    # Revision reasoning surfaced
    assert "Math layer shows near-symmetric" in html_text
    # Pass 2 catalyst verdict surfaced
    assert "VERIFIED" in html_text
    assert "Q1 earnings" in html_text


def test_html_dashboard_clean_run_no_reliability_bar(tmp_path):
    """Clean profile → no reliability bar in HTML output."""
    from src.engine import AIPassOutput
    from src.reporter import generate_html_dashboard

    snapshot = SimpleNamespace(
        ticker="CLEAN",
        timestamp=__import__("datetime").datetime(2026, 5, 24, 14, 30),
        spot=100.0, ytd_return=0.30,
    )
    vol_profile = _make_vol_profile(alpha_plus_beta=0.70, divergence=5.0)
    vol_profile.blended_sigma = 0.40
    base_signals_full = [_make_signal("HIGH") for _ in range(12)]
    method_check = {"refused": False, "flags": [], "table": []}
    backtest = {"sufficient_data": False, "n_samples": 0, "message": "N=0"}

    out = tmp_path / "clean_dashboard.html"
    generate_html_dashboard(
        out, snapshot, None, vol_profile,
        # Note: needs DriftSignal-like objects with name/mu_annual/etc;
        # base_signals goes through chart generation. Use empty list.
        [],
        None, None, method_check, backtest, [],
        conviction_dip=0.65, conviction_rally_cond=0.70,
        horizon_days=60,
    )
    html_text = out.read_text()
    assert 'class="reliability-bar"' not in html_text
